### ISSUE TITLE
Motivation for file headers

### ISSUE THREAD

**Issue by weaverba137** [sdss/python_template#6]
The coding standards associated with the template make a specific  [recommendation for file headers](http://sdss-python-template.readthedocs.io/en/latest/standards.html#file-headers), however, it is not clear where these recommendations come from, or how these values would be read or set in practice.

Also, the specific line
```python
# encoding: utf-8
```
is more commonly
```python
# -*- coding: utf-8 -*-
```

Finally, by recommending
```python
#!/usr/bin/env python
```
you're basically saying that every Python module file will be executable.  I don't *think* this is recommended practice.  The `#!` line only belongs in truly executable scripts that will be installed in a `bin/` directory.

**Comment by albireox** [comment]
I have been using the utf-8 encoding line like that forever (not sure why, it has always been like that in my new file snippet) and not seen any problem, but I'm not opposed to changing it.

I see the point in your comment about the shebang, but adding a shebang doesn't make the file executable. It does prepare it for the case that so that if you make it executable. But I think I agree that only python files in bin/ should be executable.

Thoughts?

**Comment by weaverba137** [comment]
I think that
```python
# encoding: utf-8
```
is exactly equivalent to 
```python
# -*- coding: utf-8 -*-
```
*in the Python environment*, because both contain the substring `coding: utf-8`.  However, the second form may be more widely recognized, for example by certain text editors, in addition to Python.

**Comment by weaverba137** [comment]
By the way, my views are strongly shaped by the Astropy code & documentation guidelines, so this is where I'm coming from:

 * http://docs.astropy.org/en/stable/development/codeguide.html
 * http://docs.astropy.org/en/stable/development/docguide.html

**Comment by albireox** [comment]
Those are good resources. I've added them to the further reading section.
