### ISSUE TITLE
Suggestion: Reference PEP 440 in the versioning section of the standards document.

### ISSUE THREAD

**Issue by weaverba137** [sdss/python_template#7]
[PEP 440](https://www.python.org/dev/peps/pep-0440/) documents Python versioning guidelines in detail. In particular this is a good place to read the details about `1.2.3a1`, `2.3.1b2`, `1.3.4.dev45`.

Note that it recommends `.dev`, not `dev`.

**Comment by albireox** [comment]
I've added a reference to PEP440 in the versioning section. The reason for not using periods with the suffixes is that we have found that it sometimes causes problems with PyPI, or at least the suffixes are renamed when they get uploaded there. For Marvin we decided to use `dev` instead of `.dev` and that has worked fine for us, but if somebody has opinions we can reopen this.

**Comment by weaverba137** [comment]
This is a *feature* not a bug.  There are plenty of good reason to post alpha, beta, rc, versions to PyPI.  However, there are not so many good reasons to post development versions to PyPI.  If you *really* want to post a development version to PyPI, then you should seriously consider calling it an alpha version, and using the alpha suffix.

The `.dev` suffix is useful to denote code that is under such active development that no one should have any reason to expect stability.

**Comment by albireox** [comment]
Agreed. I was not meaning that we don't use `dev`, `alpha`, etc. What I meant is that when we used `.dev` and tried to deploy that pre-release version to PyPI we had problems. I don't remember if things didn't work or simply PyPI renamed our `X.Y.Z.dev` versions to `X.Y.Zdev`, so I think we decided to remove the period in our versions for consistency.
