### ISSUE TITLE
error: 'egg_base' must be a directory name (got `python`)

### ISSUE THREAD

**Issue by nbmurphy** [sdss/python_template#9]
This issue is similar to the one discussed here
https://github.com/pypa/setuptools/issues/1136
and here
https://github.com/pypa/pip/issues/5732
It seems to only effect Python 2.7. Commenting out the line `- '2.7'` in .travis.yml fixes the problem. However, some repos still use Python 2.7, such as sdss_install through sdss4install, so this is not an ideal workaround.

**Comment by albireox** [comment]
So, this problem seem to be caused by having a `from __future__ import unicode_literals` in `setup.py`. The issue is related to `setuptools` and I don't think it has been solved. Given that we don't really use any character that is not ASCII in `setup.py` I think it's safe to remove that import from that file. I've tagged a new version.
